server:
  port: 8081


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gamma?useSSL=false
    username: gamma
    password: gemma1234
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

identity:
  jwt:
    secret: cloLptCUJGemHqbVE6^s6WMxGvVyEdW1iQRXh2P?NCNJVqd1H8B7v8RFt9gXgQL7
    prefix: Bearer
    param: Authorization

app:
  security:
    service:
      name: pec