server:
  port: 8082


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gamma
    username: gamma
    password: gemma1234
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true


